### ISSUE TITLE
Projected SGD updates for the parameters

### ISSUE THREAD

**Issue by maryami66** [google-research/tensorflow_constrained_optimization#3]
Dear authors,
As it is mentioned in "lagrangian_optimizer.py" lines 34-38, the optimizer is most similar to Algorithm 3 of the paper. I am curious if you project the parameter after the each SGD update onto the constraint surface or no.  
It seems that in the code the projection is done only for multiplier and not for the parameters. As far as I understood, this way we cannot guaranty to meet the constraint at the end.

I will appreciate if you could let me know this issue which is kinda important for me.

Thanks a lot
Maryam

**Comment by acotter** [comment]
No, we use the Lagrangian formulation (or something like it) to "push away" from the constraints by penalizing them (with the penalties being Lagrange multipliers). The only projections that are performed are for the Lagrange multipliers themselves (they must be nonnegative, for the Lagrangian, or the matrix must be left-stochastic, for the proxy-Lagrangian).
